import { ThemeConfig } from '../types';

export const themes: ThemeConfig[] = [
  {
    id: 'elegant-gold',
    name: 'Elegant Gold',
    preview: '👑',
    fontFamily: "'Poppins', sans-serif",
    headingFont: "'Playfair Display', serif",
    scriptFont: "'Great Vibes', cursive",
    primaryColor: '#B8860B',
    secondaryColor: '#1a1a2e',
    accentColor: '#D4AF37',
    bgGradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    textColor: '#f0e6d3',
    cardBg: 'rgba(26, 26, 46, 0.8)',
    overlayOpacity: 0.7
  },
  {
    id: 'rustic-blush',
    name: 'Rustic Blush',
    preview: '🌸',
    fontFamily: "'Lora', serif",
    headingFont: "'Cormorant Garamond', serif",
    scriptFont: "'Dancing Script', cursive",
    primaryColor: '#c9a96e',
    secondaryColor: '#f5e6d3',
    accentColor: '#8b6914',
    bgGradient: 'linear-gradient(135deg, #f5e6d3 0%, #f0d9c0 50%, #e8c9a0 100%)',
    textColor: '#4a3728',
    cardBg: 'rgba(255, 255, 255, 0.9)',
    overlayOpacity: 0.5
  },
  {
    id: 'modern-minimalist',
    name: 'Modern Minimalist',
    preview: '⬜',
    fontFamily: "'Montserrat', sans-serif",
    headingFont: "'Montserrat', sans-serif",
    scriptFont: "'Cormorant', serif",
    primaryColor: '#2d2d2d',
    secondaryColor: '#ffffff',
    accentColor: '#666666',
    bgGradient: 'linear-gradient(135deg, #ffffff 0%, #f8f8f8 50%, #f0f0f0 100%)',
    textColor: '#2d2d2d',
    cardBg: 'rgba(255, 255, 255, 0.95)',
    overlayOpacity: 0.3
  },
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    preview: '💜',
    fontFamily: "'Poppins', sans-serif",
    headingFont: "'Playfair Display', serif",
    scriptFont: "'Great Vibes', cursive",
    primaryColor: '#6b21a8',
    secondaryColor: '#1e1b4b',
    accentColor: '#a855f7',
    bgGradient: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4c1d95 100%)',
    textColor: '#e9d5ff',
    cardBg: 'rgba(30, 27, 75, 0.85)',
    overlayOpacity: 0.75
  },
  {
    id: 'garden-green',
    name: 'Garden Green',
    preview: '🌿',
    fontFamily: "'Lora', serif",
    headingFont: "'Cormorant Garamond', serif",
    scriptFont: "'Dancing Script', cursive",
    primaryColor: '#166534',
    secondaryColor: '#f0fdf4',
    accentColor: '#22c55e',
    bgGradient: 'linear-gradient(135deg, #f0fdf4 0%, #dcfce7 50%, #bbf7d0 100%)',
    textColor: '#14532d',
    cardBg: 'rgba(255, 255, 255, 0.9)',
    overlayOpacity: 0.4
  },
  {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    preview: '🌊',
    fontFamily: "'Poppins', sans-serif",
    headingFont: "'Playfair Display', serif",
    scriptFont: "'Great Vibes', cursive",
    primaryColor: '#1e40af',
    secondaryColor: '#eff6ff',
    accentColor: '#3b82f6',
    bgGradient: 'linear-gradient(135deg, #eff6ff 0%, #dbeafe 50%, #bfdbfe 100%)',
    textColor: '#1e3a5f',
    cardBg: 'rgba(255, 255, 255, 0.9)',
    overlayOpacity: 0.5
  },
  {
    id: 'sunset-orange',
    name: 'Sunset Orange',
    preview: '🌅',
    fontFamily: "'Montserrat', sans-serif",
    headingFont: "'Playfair Display', serif",
    scriptFont: "'Dancing Script', cursive",
    primaryColor: '#c2410c',
    secondaryColor: '#fff7ed',
    accentColor: '#f97316',
    bgGradient: 'linear-gradient(135deg, #fff7ed 0%, #fed7aa 50%, #fdba74 100%)',
    textColor: '#431407',
    cardBg: 'rgba(255, 255, 255, 0.9)',
    overlayOpacity: 0.5
  },
  {
    id: 'dark-romance',
    name: 'Dark Romance',
    preview: '🖤',
    fontFamily: "'Poppins', sans-serif",
    headingFont: "'Playfair Display', serif",
    scriptFont: "'Great Vibes', cursive",
    primaryColor: '#be123c',
    secondaryColor: '#0a0a0a',
    accentColor: '#f43f5e',
    bgGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1c1917 50%, #292524 100%)',
    textColor: '#fecdd3',
    cardBg: 'rgba(10, 10, 10, 0.85)',
    overlayOpacity: 0.8
  },
  {
    id: 'dusty-rose',
    name: 'Dusty Rose',
    preview: '🌹',
    fontFamily: "'Cormorant Garamond', serif",
    headingFont: "'Cormorant Garamond', serif",
    scriptFont: "'Great Vibes', cursive",
    primaryColor: '#9f1239',
    secondaryColor: '#fff1f2',
    accentColor: '#e11d48',
    bgGradient: 'linear-gradient(135deg, #fff1f2 0%, #ffe4e6 50%, #fecdd3 100%)',
    textColor: '#4c0519',
    cardBg: 'rgba(255, 255, 255, 0.9)',
    overlayOpacity: 0.4
  },
  {
    id: 'boho-chic',
    name: 'Boho Chic',
    preview: '🪶',
    fontFamily: "'Lora', serif",
    headingFont: "'Libre Baskerville', serif",
    scriptFont: "'Dancing Script', cursive",
    primaryColor: '#92400e',
    secondaryColor: '#fefce8',
    accentColor: '#d97706',
    bgGradient: 'linear-gradient(135deg, #fefce8 0%, #fef9c3 50%, #fef08a 100%)',
    textColor: '#451a03',
    cardBg: 'rgba(254, 252, 232, 0.9)',
    overlayOpacity: 0.4
  },
  {
    id: 'midnight-star',
    name: 'Midnight Star',
    preview: '✨',
    fontFamily: "'Montserrat', sans-serif",
    headingFont: "'Playfair Display', serif",
    scriptFont: "'Great Vibes', cursive",
    primaryColor: '#c0c0c0',
    secondaryColor: '#0c0c1d',
    accentColor: '#e2e8f0',
    bgGradient: 'linear-gradient(135deg, #0c0c1d 0%, #1a1a3e 50%, #0f0f2d 100%)',
    textColor: '#e2e8f0',
    cardBg: 'rgba(12, 12, 29, 0.85)',
    overlayOpacity: 0.8
  },
  {
    id: 'tropical-paradise',
    name: 'Tropical Paradise',
    preview: '🌺',
    fontFamily: "'Poppins', sans-serif",
    headingFont: "'Playfair Display', serif",
    scriptFont: "'Dancing Script', cursive",
    primaryColor: '#0d9488',
    secondaryColor: '#f0fdfa',
    accentColor: '#14b8a6',
    bgGradient: 'linear-gradient(135deg, #f0fdfa 0%, #ccfbf1 50%, #99f6e4 100%)',
    textColor: '#134e4a',
    cardBg: 'rgba(255, 255, 255, 0.9)',
    overlayOpacity: 0.4
  },
  {
    id: 'vintage-cream',
    name: 'Vintage Cream',
    preview: '📜',
    fontFamily: "'Libre Baskerville', serif",
    headingFont: "'Libre Baskerville', serif",
    scriptFont: "'Great Vibes', cursive",
    primaryColor: '#78716c',
    secondaryColor: '#faf5ef',
    accentColor: '#a8a29e',
    bgGradient: 'linear-gradient(135deg, #faf5ef 0%, #f5f0e8 50%, #ede8df 100%)',
    textColor: '#44403c',
    cardBg: 'rgba(250, 245, 239, 0.95)',
    overlayOpacity: 0.3
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    preview: '🌸',
    fontFamily: "'Cormorant Garamond', serif",
    headingFont: "'Cormorant Garamond', serif",
    scriptFont: "'Dancing Script', cursive",
    primaryColor: '#db2777',
    secondaryColor: '#fdf2f8',
    accentColor: '#ec4899',
    bgGradient: 'linear-gradient(135deg, #fdf2f8 0%, #fce7f3 50%, #fbcfe8 100%)',
    textColor: '#500724',
    cardBg: 'rgba(255, 255, 255, 0.9)',
    overlayOpacity: 0.4
  },
  {
    id: 'luxury-black',
    name: 'Luxury Black',
    preview: '🏆',
    fontFamily: "'Montserrat', sans-serif",
    headingFont: "'Playfair Display', serif",
    scriptFont: "'Great Vibes', cursive",
    primaryColor: '#d4af37',
    secondaryColor: '#000000',
    accentColor: '#ffd700',
    bgGradient: 'linear-gradient(135deg, #000000 0%, #1a1a1a 50%, #0d0d0d 100%)',
    textColor: '#d4af37',
    cardBg: 'rgba(0, 0, 0, 0.9)',
    overlayOpacity: 0.85
  },
  {
    id: 'lavender-dream',
    name: 'Lavender Dream',
    preview: '💐',
    fontFamily: "'Lora', serif",
    headingFont: "'Cormorant Garamond', serif",
    scriptFont: "'Dancing Script', cursive",
    primaryColor: '#7c3aed',
    secondaryColor: '#faf5ff',
    accentColor: '#a78bfa',
    bgGradient: 'linear-gradient(135deg, #faf5ff 0%, #f3e8ff 50%, #e9d5ff 100%)',
    textColor: '#3b0764',
    cardBg: 'rgba(255, 255, 255, 0.9)',
    overlayOpacity: 0.4
  },
  {
    id: 'earth-tone',
    name: 'Earth Tone',
    preview: '🍂',
    fontFamily: "'Poppins', sans-serif",
    headingFont: "'Libre Baskerville', serif",
    scriptFont: "'Dancing Script', cursive",
    primaryColor: '#78350f',
    secondaryColor: '#fef3c7',
    accentColor: '#b45309',
    bgGradient: 'linear-gradient(135deg, #fef3c7 0%, #fde68a 50%, #fcd34d 100%)',
    textColor: '#451a03',
    cardBg: 'rgba(254, 243, 199, 0.9)',
    overlayOpacity: 0.5
  },
  {
    id: 'arctic-ice',
    name: 'Arctic Ice',
    preview: '❄️',
    fontFamily: "'Montserrat', sans-serif",
    headingFont: "'Playfair Display', serif",
    scriptFont: "'Great Vibes', cursive",
    primaryColor: '#0369a1',
    secondaryColor: '#f0f9ff',
    accentColor: '#0ea5e9',
    bgGradient: 'linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 50%, #bae6fd 100%)',
    textColor: '#0c4a6e',
    cardBg: 'rgba(255, 255, 255, 0.9)',
    overlayOpacity: 0.4
  },
  {
    id: 'copper-rose',
    name: 'Copper & Rose',
    preview: '🥀',
    fontFamily: "'Cormorant Garamond', serif",
    headingFont: "'Cormorant Garamond', serif",
    scriptFont: "'Great Vibes', cursive",
    primaryColor: '#b45309',
    secondaryColor: '#fdf4ff',
    accentColor: '#c084fc',
    bgGradient: 'linear-gradient(135deg, #fdf4ff 0%, #fae8ff 50%, #f5d0fe 100%)',
    textColor: '#4a044e',
    cardBg: 'rgba(255, 255, 255, 0.9)',
    overlayOpacity: 0.4
  },
  {
    id: 'safari-adventure',
    name: 'Safari Adventure',
    preview: '🦁',
    fontFamily: "'Lora', serif",
    headingFont: "'Libre Baskerville', serif",
    scriptFont: "'Dancing Script', cursive",
    primaryColor: '#854d0e',
    secondaryColor: '#fefce8',
    accentColor: '#a16207',
    bgGradient: 'linear-gradient(135deg, #fefce8 0%, #fef9c3 50%, #fef08a 100%)',
    textColor: '#3f3f00',
    cardBg: 'rgba(254, 252, 232, 0.9)',
    overlayOpacity: 0.5
  },
  {
    id: 'pearl-white',
    name: 'Pearl White',
    preview: '🤍',
    fontFamily: "'Cormorant Garamond', serif",
    headingFont: "'Cormorant Garamond', serif",
    scriptFont: "'Great Vibes', cursive",
    primaryColor: '#9ca3af',
    secondaryColor: '#ffffff',
    accentColor: '#d1d5db',
    bgGradient: 'linear-gradient(135deg, #ffffff 0%, #f9fafb 50%, #f3f4f6 100%)',
    textColor: '#374151',
    cardBg: 'rgba(255, 255, 255, 0.95)',
    overlayOpacity: 0.2
  },
  {
    id: 'emerald-night',
    name: 'Emerald Night',
    preview: '💚',
    fontFamily: "'Poppins', sans-serif",
    headingFont: "'Playfair Display', serif",
    scriptFont: "'Great Vibes', cursive",
    primaryColor: '#059669',
    secondaryColor: '#022c22',
    accentColor: '#10b981',
    bgGradient: 'linear-gradient(135deg, #022c22 0%, #064e3b 50%, #065f46 100%)',
    textColor: '#a7f3d0',
    cardBg: 'rgba(2, 44, 34, 0.85)',
    overlayOpacity: 0.75
  },
  {
    id: 'coral-reef',
    name: 'Coral Reef',
    preview: '🐚',
    fontFamily: "'Montserrat', sans-serif",
    headingFont: "'Playfair Display', serif",
    scriptFont: "'Dancing Script', cursive",
    primaryColor: '#e11d48',
    secondaryColor: '#fff1f2',
    accentColor: '#fb7185',
    bgGradient: 'linear-gradient(135deg, #fff1f2 0%, #ffe4e6 50%, #fecdd3 100%)',
    textColor: '#4c0519',
    cardBg: 'rgba(255, 255, 255, 0.9)',
    overlayOpacity: 0.4
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    preview: '🌟',
    fontFamily: "'Lora', serif",
    headingFont: "'Cormorant Garamond', serif",
    scriptFont: "'Great Vibes', cursive",
    primaryColor: '#b8860b',
    secondaryColor: '#fffbeb',
    accentColor: '#f59e0b',
    bgGradient: 'linear-gradient(135deg, #fffbeb 0%, #fef3c7 50%, #fde68a 100%)',
    textColor: '#451a03',
    cardBg: 'rgba(255, 251, 235, 0.9)',
    overlayOpacity: 0.4
  }
];
